### ISSUE TITLE
[bug] the plugin cannot be fully shown on the website

### ISSUE THREAD

**Issue by xuzh0u** [LinHeLurking/Sep_Calendar#1]
![image](https://user-images.githubusercontent.com/42308170/133210572-066f9d24-d2ab-424b-ab92-782913a67637.png)

After I ticked the box, I found that I cannot scroll down to meet any button that may submit the form.

My browser is Edge on Windows 10. Do you need any other infomation?

**Comment by LinHeLurking** [comment]
(Sorry for late comments )
I think it might be some error about loading. Try to refresh the page.

**Comment by xuzh0u** [comment]
At least it shows the button now lol
