### ISSUE TITLE
部分课程生成错误

### ISSUE THREAD

**Issue by sbwww** [LinHeLurking/Sep_Calendar#2]
首先感谢作者

最近使用时发现，**开课周数无规律**的课程会生成错误，例如

![image](https://user-images.githubusercontent.com/45259695/187074180-502a51cc-475f-4e98-b3ee-be6a78de80c7.png)

生成错误的 .ics 文件如下

```
BEGIN:VEVENT
CREATED:20220828T115753Z
DTSTAMP:20220828T115753Z
SUMMARY:信息检索导论
DESCRIPTION:
LOCATION:教一楼306
TZID:Asia/Shanghai
SEQUENCE:0
UID:354c8180-01d5-42e4-b196-5350ae3d6302
RRULE:FREQ=WEEKLY;UNTIL=20221219T080000;INTERVAL=1,BYDAY=
DTSTART;TZID=Asia/Shanghai:NaNNaNNaNTNaNNaNNaN
DTEND;TZID=Asia/Shanghai:NaNNaNNaNTNaNNaNNaN
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT0H15M0S
X-WR-ALARMUID:2882441a-4552-45cb-9557-fa7ba3ac7d35
UID:b1aae4ee-4b72-44a0-ab59-ecaca975fcbb
END:VALARM
END:VEVENT
```

可以看到 `BYDAY` 是空的，并且有两处 NAN。粗略地看了一下代码，感觉爬数据的部分可以用，但生成 ICS 的时候出现了问题

**Comment by LinHeLurking** [comment]
## BYDAY 是空的

这个是我当时设计的时候只考虑了规则的每周重复和隔周重复的情形，详见[这块代码](https://github.com/LinHeLurking/Sep_Calendar/blob/99e6c290a63e18d8b7a55ce8bae201b028b604aa/sel.user.js#L325-L334)。

如果要修正这个错误，可以在这里加一个判断，如果是完全不规则的周次，则不使用按周重复的规则，而是拆分开成为若干单个的事件。

## 出现 `NaN`

应该是对"当前课程是一天中的第几节课"的解析有问题，详见[这块代码](https://github.com/LinHeLurking/Sep_Calendar/blob/99e6c290a63e18d8b7a55ce8bae201b028b604aa/sel.user.js#L118-L151)。
改一下选择器应该就能抓出来正确的数据了。

但是现在我已经不选课了，那个全部待选课程的页面我是进不去的，所以我也没办法帮你测试 😢 。
只能给你说一下大致思路让你自己去改了 😢 。

**Comment by sbwww** [comment]
破案了

https://github.com/LinHeLurking/Sep_Calendar/blob/99e6c290a63e18d8b7a55ce8bae201b028b604aa/sel.user.js#L23

系统里是星期日，这边修改以后 `BYDAY` 正常，也不会有 NaN

剩下我看看能不能把不规则的周次的问题改好

**Comment by LinHeLurking** [comment]
See #3

**Comment by LinHeLurking** [comment]
目前应该都修好了，可以试试看

**Comment by sbwww** [comment]
cool 😎 
再次感谢
